// Code generated by MockGen. DO NOT EDIT.
// Source: ../advert/rest.go
//
// Generated by this command:
//
//	mockgen -destination=./advert/mock_accessors.go -package=advert_mock -source=../advert/rest.go Accessors
//

// Package advert_mock is a generated GoMock package.
package advert_mock

import (
	reflect "reflect"

	pkg "github.com/SleepNFire/mediakeys/ad-serving/pkg"
	gomock "go.uber.org/mock/gomock"
)

// MockCacheAccessor is a mock of CacheAccessor interface.
type MockCacheAccessor struct {
	ctrl     *gomock.Controller
	recorder *MockCacheAccessorMockRecorder
}

// MockCacheAccessorMockRecorder is the mock recorder for MockCacheAccessor.
type MockCacheAccessorMockRecorder struct {
	mock *MockCacheAccessor
}

// NewMockCacheAccessor creates a new mock instance.
func NewMockCacheAccessor(ctrl *gomock.Controller) *MockCacheAccessor {
	mock := &MockCacheAccessor{ctrl: ctrl}
	mock.recorder = &MockCacheAccessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheAccessor) EXPECT() *MockCacheAccessorMockRecorder {
	return m.recorder
}

// Exist mocks base method.
func (m *MockCacheAccessor) Exist(id string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exist", id)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Exist indicates an expected call of Exist.
func (mr *MockCacheAccessorMockRecorder) Exist(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exist", reflect.TypeOf((*MockCacheAccessor)(nil).Exist), id)
}

// Find mocks base method.
func (m *MockCacheAccessor) Find(id string) (*pkg.AdvertData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", id)
	ret0, _ := ret[0].(*pkg.AdvertData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockCacheAccessorMockRecorder) Find(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockCacheAccessor)(nil).Find), id)
}

// Store mocks base method.
func (m *MockCacheAccessor) Store(advert *pkg.AdvertData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", advert)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockCacheAccessorMockRecorder) Store(advert any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockCacheAccessor)(nil).Store), advert)
}

// MockImpressionAccessor is a mock of ImpressionAccessor interface.
type MockImpressionAccessor struct {
	ctrl     *gomock.Controller
	recorder *MockImpressionAccessorMockRecorder
}

// MockImpressionAccessorMockRecorder is the mock recorder for MockImpressionAccessor.
type MockImpressionAccessorMockRecorder struct {
	mock *MockImpressionAccessor
}

// NewMockImpressionAccessor creates a new mock instance.
func NewMockImpressionAccessor(ctrl *gomock.Controller) *MockImpressionAccessor {
	mock := &MockImpressionAccessor{ctrl: ctrl}
	mock.recorder = &MockImpressionAccessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImpressionAccessor) EXPECT() *MockImpressionAccessorMockRecorder {
	return m.recorder
}

// GetNumber mocks base method.
func (m *MockImpressionAccessor) GetNumber(id string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNumber", id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNumber indicates an expected call of GetNumber.
func (mr *MockImpressionAccessorMockRecorder) GetNumber(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNumber", reflect.TypeOf((*MockImpressionAccessor)(nil).GetNumber), id)
}

// Inc mocks base method.
func (m *MockImpressionAccessor) Inc(id string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Inc", id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Inc indicates an expected call of Inc.
func (mr *MockImpressionAccessorMockRecorder) Inc(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inc", reflect.TypeOf((*MockImpressionAccessor)(nil).Inc), id)
}
