// Code generated by MockGen. DO NOT EDIT.
// Source: ../printing/grpc.go
//
// Generated by this command:
//
//	mockgen -destination=./printing/mock_cache_accessor.go -package=printing_mock -source=../printing/grpc.go CacheAccessor
//

// Package printing_mock is a generated GoMock package.
package printing_mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCacheAccessor is a mock of CacheAccessor interface.
type MockCacheAccessor struct {
	ctrl     *gomock.Controller
	recorder *MockCacheAccessorMockRecorder
}

// MockCacheAccessorMockRecorder is the mock recorder for MockCacheAccessor.
type MockCacheAccessorMockRecorder struct {
	mock *MockCacheAccessor
}

// NewMockCacheAccessor creates a new mock instance.
func NewMockCacheAccessor(ctrl *gomock.Controller) *MockCacheAccessor {
	mock := &MockCacheAccessor{ctrl: ctrl}
	mock.recorder = &MockCacheAccessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheAccessor) EXPECT() *MockCacheAccessorMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockCacheAccessor) Find(id string) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", id)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockCacheAccessorMockRecorder) Find(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockCacheAccessor)(nil).Find), id)
}

// Inc mocks base method.
func (m *MockCacheAccessor) Inc(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Inc", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Inc indicates an expected call of Inc.
func (mr *MockCacheAccessorMockRecorder) Inc(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inc", reflect.TypeOf((*MockCacheAccessor)(nil).Inc), id)
}
